name: niagara4
summary: Niagara Framework
description: Niagara IoT Framework
version: "4.13.3.48"
adopt-info: overlay

base: core24
grade: devel
confinement: devmode

platforms:
  amd64:

apps:
  niagarad:
    command: bin/niagarad-wrapper
    daemon: simple
    environment:
      LD_LIBRARY_PATH: $SNAP/bin:$SNAP_COMMON/lib:$SNAP_COMMON/Niagara4.13/tridium/shared
      HOME: $SNAP_COMMON
    plugs: [network, network-bind]

parts:
  jre:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/azul-jre-linux-amd64.dist
    source-type: zip
    override-build: |
      craftctl default
      mv $CRAFT_PART_INSTALL/lib/ext $CRAFT_PART_INSTALL/lib/ext-bundled
    organize:
      "*": jre/
  deps:
    plugin: nil
    stage-packages:
      - util-linux
  core:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/nre-core-linux-x64.dist
    source-type: zip
    organize:
      "*": bin/
    stage:
      - -bin/ext/jxbrowser
      - -bin/nsupport
      - -bin/libdsfspi.so
      - -bin/ext/nre.jar
      - "*"
    override-stage: |
      craftctl default
      chmod +x bin/*

  nsupport:
    plugin: make
    source: nsupport
    organize:
      nsupport: bin/

  config:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/nre-config-linux-x64.dist
    source-type: zip
    stage:
      - defaults
      - etc
      - security

  overlay:
    plugin: dump
    source: overlay
    override-stage: |
      craftctl default
      craftctl set version="$(craftctl get version)-$(git rev-parse --short HEAD)"

layout:
  /etc/niagara:
    bind: $SNAP_COMMON/sysroot/etc/niagara
  $SNAP/etc:
    bind: $SNAP_COMMON/etc
  $SNAP/security/certificates:
    bind: $SNAP_COMMON/security/certificates
  $SNAP/security/licenses:
    bind: $SNAP_COMMON/security/licenses
  $SNAP/modules:
    bind: $SNAP_COMMON/modules
  $SNAP/jre/lib/ext:
    bind: $SNAP_COMMON/jre/lib/ext
