#!/bin/bash -e
mkdir -p $SNAP_COMMON/sysroot/etc/niagara
mkdir -p $SNAP_COMMON/etc
mkdir -p $SNAP_COMMON/security/licenses
mkdir -p $SNAP_COMMON/modules
mkdir -p $SNAP_COMMON/Niagara4.13/tridium/daemon
mkdir -p $SNAP_COMMON/Niagara4.13/vykon/daemon

cp $SNAP/defaults/daemon.properties $SNAP_COMMON/Niagara4.13/tridium/daemon/
cp $SNAP/defaults/daemon.properties $SNAP_COMMON/Niagara4.13/vykon/daemon

chown 5011:5011 -R $SNAP_COMMON
chown 5011:5011 -R $SNAP_DATA

snapctl set \
	debug=0